logging:
  path: /log/
  file: log.log 
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: true
#懒加载
#spring.jpa.open-in-view=true